### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by Wyzix33** [chrisdavies/alite#1]
Hi, first of all i want to thank you for this great utility, i use it and had no problems with it and i want to ask you if there is some way to add the context for this keyword, here is an example:
`var a = function () {
    alite({ 
        url: '/api/foo/bar',
        method: 'POST',
        data: { foo: 'bar' }
    }).then(function (result) {
        this.process(result);
    })
}
a.prototype =  {
   process: function(result) {
       ... do something with the result ...
   },
.... 

}`
this.process is not available so i have to assign a new variable to this "var _this = this; " and call the _this.process(value). is there any way i can pass the scope without creating this new variable?
Thanks

**Comment by chrisdavies** [comment]
Glad you like it!

Sounds like you're running into a typical JavaScript limitation. If you use ES6 via Babel or something, you could get around this in a variety of ways. If you're just using ES5, here are a few solutions:

``` js
var a = function () {
  alite({ 
    url: '/api/foo/bar',
    method: 'POST',
    data: { foo: 'bar' }
  }).then(this.process.bind(this))
}

a.prototype = {
  process: function(result) {
    // ... do something with the result ...
  },
  // etc...
}
```

Of course, you could also not use prototypal inheritance at all... I never use it these days.

``` js
// Just pass the process function into a
function a(process) {
  alite({ 
    url: '/api/foo/bar',
    method: 'POST',
    data: { foo: 'bar' }
  }).then(process)
}
```

Or even better:

``` js
// Don't pass anything into a, and just return the alite promise:
function a() {
  return alite({ 
    url: '/api/foo/bar',
    method: 'POST',
    data: { foo: 'bar' }
  })
}

// And use it like this:
a().then(function (result) {
   // .. do something with the result ...
})
```
