### ISSUE TITLE
multipart/form-data

### ISSUE THREAD

**Issue by Wyzix33** [chrisdavies/alite#2]
Hi, i have added a multipart/form-data to a test project (it has some text inputs and one file input) and i am using this function onsubmit

``` JAVASCRIPT
function post(url,form) {
  var data = new FormData(form);
  return alite({
                url: url,
                method: 'post',
                data: data,
                raw: true
            });
}
```

is this the right way to do this or do i have to specify Content-Type, Content-Disposition ...
Thank you

**Comment by chrisdavies** [comment]
I'm doing an AWS upload just using this:

```
url: presigned.url,
method: 'post',
data: data,
raw: true,
```
