### ISSUE TITLE
Cross-Origin Request Blocked issue

### ISSUE THREAD

**Issue by Wyzix33** [chrisdavies/alite#4]
Hi, i need to get some info from 
http://openapi.ro/api/companies/13548146.json
and if i use alite like this:

```
alite({
url: 'http://openapi.ro/api/companies/13548146.json',  
method: 'get',
dataType: 'jsonp'
}).then(function (result) { console.log(result); });
```

i get 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://openapi.ro/api/companies/13548146.json. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

but it works with 

```
$.ajax({
    type: 'get',
    url: 'http://openapi.ro/api/companies/13548146.json',
    dataType: 'jsonp',
    success: function(data) {
        console.log(data["state"]);
        }
})
```

any hints on this

Thanks

**Comment by Wyzix33** [comment]
I captured the headers sent by alite:

```
OPTIONS /api/companies/13548146.json HTTP/1.1
Host: openapi.ro
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Origin: http://conta.localhost
Access-Control-Request-Method: GET
Access-Control-Request-Headers: content-type
Connection: keep-alive
```

and the headers sent by jquery:

```

GET /api/companies/1.json?callback=jQuery2200682682120183269_1461170653119&_=1461170653126 HTTP/1.1
Host: openapi.ro
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://conta.localhost/
Cookie: __utma=158443492.1277317081.1461163089.1461163089.1461163089.1; __utmc=158443492; __utmz=158443492.1461163089.1.1.utmcsr=google|utmccn=(organic)|utmcmd=organic|utmctr=(not%20provided)
Connection: keep-alive
```

maybe you can figure it out why this happens.
Thanks

**Comment by chrisdavies** [comment]
Hm. I haven't had to use JSONP in quite a while, but it's safe to say that `alite` doesn't support it. Basically, with JSONP, what you're really doing is including a new `<script src="someurl"></script>` tag into your HTML, where `someurl` is the URL of the JSONP resource. When that script loads, it will call your callback. Note the URL sent by jQuery has a `?callback=...` portion.

SO yeah, if you need JSONP, alite isn't really the tool for you. On the other hand, it's not terribly difficult to roll your own. Basically, it would look something like this:

``` js

window.stuffLoaded = function (result) {
   console.log(result)
}

function jsonp(url, callbackName) {
   var el = document.createElement('script')
   el.src = url + '?callback=' + callbackName
   document.body.appendChild(el)
}

// Invoke your JSONP call
jsonp('http://example', 'stuffLoaded')

```

That's the most basic implementation. jQuery does magic under the hood, such as generating functions for you in the global scope so you don't litter it yourself. I imagine they also clean up the script tags and global functions at some point, though I'm not sure.

**Comment by Wyzix33** [comment]
Thank you, i haven't used jsonp before, and i don't want to use jQuery, so this jsonp function does the job :+1:
