### ISSUE TITLE
Loading while retrieving data

### ISSUE THREAD

**Issue by Wyzix33** [chrisdavies/alite#5]
Hi, I've added one loading element to my page and i want to display it while waiting for response, 
I am using alite.min.js and i change it like this:

```
//to show my element PSI.Utils.loading is a simple function that hide/show my loading element
new Promise(function(n,r){PSI.Utils.loading(true);var s=... 

//to hide my loading element
s.onreadystatechange=function(){4==s.readyState&&(s.status>=200&&s.status<300?(n(a(s)),PSI.Utils.loading(false)):r(a(s)),(PSI.Utils.curl.ajaxStop||t)(s,e))}
```

Is this correct? Or is there a better way to do this?
The problem is that it won't hide for 404's responses... I could do that:

`s.onreadystatechange=function(){4==s.readyState&&(s.status>=200&&s.status<300?(n(a(s)),PSI.Utils.loading(false)):(r(a(s),PSI.Utils.loading(false))),(PSI.Utils.curl.ajaxStop||t)(s,e))}` 

but it doesn't seem OK to me :)
Thanks

**Comment by chrisdavies** [comment]
Hey. Sorry for the long delay... been a super busy week...

I'd use this:
https://github.com/chrisdavies/alite#global-ajax-notifications-ajaxstartajaxstop

``` js
var outstandingRequests = 0;
alite.ajaxStart = function (xhr, opts) {
   ++outstandingRequests;
   // Show my processing indicator...
};

alite.ajaxStop = function (xhr, opts) {
  if (--outstandingRequests <= 0) {
    // Hide my processing indicator
  }
};
```

Might need to do some check to ensure outstandingRequests never goes negative. It shouldn't, but you know...

**Comment by chrisdavies** [comment]
I should note that in the above example, alite is assumed to be a global Alite instance that you've created somewhere.

**Comment by Wyzix33** [comment]
Great ! It's working! Thank you again!
